<?php 
$email = $_GET['em'];
$senha = $_GET['se'];
$vidas = $_GET['vid'];
$conti0 = $_GET['conti0'];
$conti1 = $_GET['conti1'];
$conti2 = $_GET['conti2'];
$conti3 = $_GET['conti3'];
$conti4 = $_GET['conti4'];
$inv1 = $_GET['inv1'];
$inv2 = $_GET['inv2'];
$inv3 = $_GET['inv3'];
$inv4 = $_GET['inv4'];
$inv5 = $_GET['inv5'];
$inv6 = $_GET['inv6'];
$inv7 = $_GET['inv7'];
$inv8 = $_GET['inv8'];
$inv9 = $_GET['inv9'];
$inv10 = $_GET['inv10'];
$paises0 = $_GET['paises0'];
$paises1 = $_GET['paises1'];
$paises2 = $_GET['paises2'];
$paises3 = $_GET['paises3'];
$paises4 = $_GET['paises4'];
$paises5 = $_GET['paises5'];
$paises6 = $_GET['paises6'];
$paises7 = $_GET['paises7'];
$paises8 = $_GET['paises8'];
$paises9 = $_GET['paises9'];
$paises10 = $_GET['paises10'];
$paises11 = $_GET['paises11'];
$paises12 = $_GET['paises12'];
$paises13 = $_GET['paises13'];
$paises14 = $_GET['paises14'];
$paises15 = $_GET['paises15'];
$paises16 = $_GET['paises16'];
$paises17 = $_GET['paises17'];
$paises18 = $_GET['paises18'];
$paises19 = $_GET['paises19'];
$paises20 = $_GET['paises20'];
$paises21 = $_GET['paises21'];
$paises22 = $_GET['paises22'];
$paises23 = $_GET['paises23'];
$paises24 = $_GET['paises24'];
require("config.php");
$conex = new PDO("mysql:host=$servidor;dbname=$basedados",
$usuario,
$senha);
$conexao = $conex->prepare("UPDATE jogador set vidas=:nvidas where email = '{$email}';");
$params = array(":nvidas" => $vidas);
$conexao->execute($params);
$conexao = $conex->prepare("UPDATE jogador set conti0=:nconti0 where email = '{$email}'");
$params = array(":nconti0" => $conti0);
$conexao->execute($params);
$conexao = $conex->prepare("UPDATE jogador set conti1=:nconti1 where email = '{$email}'");
$params = array(":nconti1" => $conti1);
$conexao->execute($params);
$conexao = $conex->prepare("UPDATE jogador set conti2=:nconti2 where email = '{$email}'");
$params = array(":nconti2" => $conti2);
$conexao->execute($params);
$conexao = $conex->prepare("UPDATE jogador set conti3=:nconti3 where email = '{$email}'");
$params = array(":nconti3" => $conti3);
$conexao->execute($params);
$conexao = $conex->prepare("UPDATE jogador set conti4=:nconti4 where email = '{$email}'");
$params = array(":nconti4" => $conti4);
$conexao->execute($params);
$conexao = $conex->prepare("UPDATE jogador set inv1=:ninv1 where email = '{$email}'");
$params = array(":ninv1" => $inv1);
$conexao->execute($params);
$conexao = $conex->prepare("UPDATE jogador set inv2=:ninv2 where email = '{$email}'");
$params = array(":ninv2" => $inv2);
$conexao->execute($params);
$conexao = $conex->prepare("UPDATE jogador set inv3=:ninv3 where email = '{$email}'");
$params = array(":ninv3" => $inv3);
$conexao->execute($params);
$conexao = $conex->prepare("UPDATE jogador set inv4=:ninv4 where email = '{$email}'");
$params = array(":ninv4" => $inv4);
$conexao->execute($params);
$conexao = $conex->prepare("UPDATE jogador set inv5=:ninv5 where email = '{$email}'");
$params = array(":ninv5" => $inv5);
$conexao->execute($params);
$conexao = $conex->prepare("UPDATE jogador set inv6=:ninv6 where email = '{$email}'");
$params = array(":ninv6" => $inv6);
$conexao->execute($params);
$conexao = $conex->prepare("UPDATE jogador set inv7=:ninv7 where email = '{$email}'");
$params = array(":ninv7" => $inv7);
$conexao->execute($params);
$conexao = $conex->prepare("UPDATE jogador set inv8=:ninv8 where email = '{$email}'");
$params = array(":ninv8" => $inv8);
$conexao->execute($params);
$conexao = $conex->prepare("UPDATE jogador set inv9=:ninv9 where email = '{$email}'");
$params = array(":ninv9" => $inv9);
$conexao->execute($params);
$conexao = $conex->prepare("UPDATE jogador set inv10=:ninv10 where email = '{$email}'");
$params = array(":ninv10" => $inv10);
$conexao->execute($params);
$conexao = $conex->prepare("UPDATE jogador set paises0=:npaises0 where email = '{$email}'");
$params = array(":npaises0" => $paises0);
$conexao->execute($params);
$conexao = $conex->prepare("UPDATE jogador set paises1=:npaises1 where email = '{$email}'");
$params = array(":npaises1" => $paises1);
$conexao->execute($params);
$conexao = $conex->prepare("UPDATE jogador set paises2=:npaises2 where email = '{$email}'");
$params = array(":npaises2" => $paises2);
$conexao->execute($params);
$conexao = $conex->prepare("UPDATE jogador set paises3=:npaises3 where email = '{$email}'");
$params = array(":npaises3" => $paises3);
$conexao->execute($params);
$conexao = $conex->prepare("UPDATE jogador set paises4=:npaises4 where email = '{$email}'");
$params = array(":npaises4" => $paises4);
$conexao->execute($params);
$conexao = $conex->prepare("UPDATE jogador set paises5=:npaises5 where email = '{$email}'");
$params = array(":npaises5" => $paises5);
$conexao->execute($params);
$conexao = $conex->prepare("UPDATE jogador set paises6=:npaises6 where email = '{$email}'");
$params = array(":npaises6" => $paises6);
$conexao->execute($params);
$conexao = $conex->prepare("UPDATE jogador set paises7=:npaises7 where email = '{$email}'");
$params = array(":npaises7" => $paises7);
$conexao->execute($params);
$conexao = $conex->prepare("UPDATE jogador set paises8=:npaises8 where email = '{$email}'");
$params = array(":npaises8" => $paises8);
$conexao->execute($params);
$conexao = $conex->prepare("UPDATE jogador set paises9=:npaises9 where email = '{$email}'");
$params = array(":npaises9" => $paises9);
$conexao->execute($params);
$conexao = $conex->prepare("UPDATE jogador set paises10=:npaises10 where email = '{$email}'");
$params = array(":npaises10" => $paises10);
$conexao->execute($params);
$conexao = $conex->prepare("UPDATE jogador set paises11=:npaises11 where email = '{$email}'");
$params = array(":npaises11" => $paises11);
$conexao->execute($params);
$conexao = $conex->prepare("UPDATE jogador set paises12=:npaises12 where email = '{$email}'");
$params = array(":npaises12" => $paises12);
$conexao->execute($params);
$conexao = $conex->prepare("UPDATE jogador set paises13=:npaises13 where email = '{$email}'");
$params = array(":npaises13" => $paises13);
$conexao->execute($params);
$conexao = $conex->prepare("UPDATE jogador set paises14=:npaises14 where email = '{$email}'");
$params = array(":npaises14" => $paises14);
$conexao->execute($params);
$conexao = $conex->prepare("UPDATE jogador set paises15=:npaises15 where email = '{$email}'");
$params = array(":npaises15" => $paises15);
$conexao->execute($params);
$conexao = $conex->prepare("UPDATE jogador set paises16=:npaises16 where email = '{$email}'");
$params = array(":npaises16" => $paises16);
$conexao->execute($params);
$conexao = $conex->prepare("UPDATE jogador set paises17=:npaises17 where email = '{$email}'");
$params = array(":npaises17" => $paises17);
$conexao->execute($params);
$conexao = $conex->prepare("UPDATE jogador set paises18=:npaises18 where email = '{$email}'");
$params = array(":npaises18" => $paises18);
$conexao->execute($params);
$conexao = $conex->prepare("UPDATE jogador set paises19=:npaises19 where email = '{$email}'");
$params = array(":npaises19" => $paises19);
$conexao->execute($params);
$conexao = $conex->prepare("UPDATE jogador set paises20=:npaises20 where email = '{$email}'");
$params = array(":npaises20" => $paises20);
$conexao->execute($params);
$conexao = $conex->prepare("UPDATE jogador set paises21=:npaises21 where email = '{$email}'");
$params = array(":npaises21" => $paises21);
$conexao->execute($params);
$conexao = $conex->prepare("UPDATE jogador set paises22=:npaises22 where email = '{$email}'");
$params = array(":npaises22" => $paises22);
$conexao->execute($params);
$conexao = $conex->prepare("UPDATE jogador set paises23=:npaises23 where email = '{$email}'");
$params = array(":npaises23" => $paises23);
$conexao->execute($params);
$conexao = $conex->prepare("UPDATE jogador set paises24=:npaises24 where email = '{$email}'");
$params = array(":npaises24" => $paises24);
$conexao->execute($params);
echo 'true';
?>